### ISSUE TITLE
nltk.tokenize.moses no longer available

### ISSUE THREAD

**Issue by petri** [jmyrberg/finnlem#1]
Trying to use finnlem results in error:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from model_wrappers import Seq2Seq
  File "/Users/petri/Code/finnlem/src/model_wrappers.py", line 13, in <module>
    from nltk.tokenize.moses import MosesDetokenizer
ModuleNotFoundError: No module named 'nltk.tokenize.moses'
```

This is because MosesTokenizer has been moved out of NLTK due to licensing issues. See for example
https://github.com/pytorch/text/issues/306 .

Apparently `sacremoses` package is now recommended as replacement.

**Comment by jmyrberg** [comment]
Hi Petri,

Sorry for the late reply, and thanks for reporting this. Since this was just a hobby project, I was expecting that something would break up at some point :) 

But luckily, I was happy to see that the [Turku NLP Group](https://turkunlp.org/) had just recently released a [paper](http://universaldependencies.org/conll18/proceedings/pdf/K18-2013.pdf), and the related [neural parser](https://turkunlp.org/Turku-neural-parser-pipeline/), which (afaik) uses a similar approach for lemmatization. So, unless you just want to learn how the seq2seq model works here, I would recommend using their parser for actual lemmatization tasks.

Hope this helps!
